name: 'CI Tests'

on:
  push:
    branches:
    - 'investigation/*'

jobs:
  static_secrets:
    runs-on: ubuntu-latest
    name: Fetch static secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch static secrets from AKeyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        static-secrets: '{"/DevTools/my-static-secret":"my_static_secret"}'

    - name: Verify Job Outputs
      run: echo "Your output secret is ${{ steps.fetch-secrets.my_static_secret }}"

    - name: Verify Environment Variables
      run: echo "Your environment secret is ${{ env.my_static_secret }}"

  aws_dynamic_secrets_default:
    runs-on: ubuntu-latest
    name: AWS dynamic secrets (default)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from AKeyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/test-grib":"aws_dynamic_secrets"}'

    - name: Verify Job Outputs using jq
      run: |
        echo "[Job Output] Your output secret is ${{ steps.fetch-secrets.outputs.aws_dynamic_secrets }}"
        echo "Manually parsed ID:" 
        echo '${{ steps.fetch-secrets.outputs.aws_dynamic_secrets }}' | jq '.id'
        echo "Manually parsed USER:" 
        echo '${{ steps.fetch-secrets.outputs.aws_dynamic_secrets }}' | jq '.user'
        echo "Manually parsed TTL_IN_MINUTES:" 
        echo '${{ steps.fetch-secrets.outputs.aws_dynamic_secrets }}' | jq '.ttl_in_minutes'
        echo "Manually parsed PASSWORD:"
        echo '${{ steps.fetch-secrets.outputs.aws_dynamic_secrets }}' | jq '.password'

    - name: Verify Environment Variables using jq
      run: |
        echo "[Env Var] Your environment secret is ${{ env.aws_dynamic_secrets }}"
        echo "Manually parsed ID:"
        echo '${{ env.aws_dynamic_secrets }}' | jq '.id'
        echo "Manually parsed USER:"
        echo '${{ env.aws_dynamic_secrets }}' | jq '.user'
        echo "Manually parsed TTL_IN_MINUTES:"
        echo '${{ env.aws_dynamic_secrets }}' | jq '.ttl_in_minutes'
        echo "Manually parsed PASSWORD:"
        echo '${{ env.aws_dynamic_secrets }}' | jq '.password'
        
    - name: EXTRA 1 - Manually Export Secrets Using jq
      run: |
        echo '${{ steps.fetch-secrets.outputs.aws_dynamic_secrets }}' | jq -r 'to_entries|map("AKEYLESS_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV

    - name: EXTRA 2 - Verify Exported Variables
      run: |
        echo "access_key_id: ${{ env.AKEYLESS_access_key_id }}"
        echo "id: ${{ env.AKEYLESS_id }}"
        echo "secret_access_key: ${{ env.AKEYLESS_secret_access_key }}"
        echo "security_token: ${{ env.AKEYLESS_security_token }}"
        echo "ttl_in_minutes: ${{ env.AKEYLESS_ttl_in_minutes }}"
        echo "type: ${{ env.AKEYLESS_type }}"
        echo "user: ${{ env.AKEYLESS_user }}"

  aws_dynamic_secrets_parsed:
    runs-on: ubuntu-latest
    name: AWS dynamic secrets (parsed)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from Akleyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/test-grib":""}' # no prefix on output names
        parse-dynamic-secrets: true

    - name: Verify Job Outputs
      run: |
        echo "access_key_id: ${{ steps.fetch-secrets.outputs.access_key_id }}"
        echo "id: ${{ steps.fetch-secrets.outputs.id }}"
        echo "secret_access_key: ${{ steps.fetch-secrets.outputs.secret_access_key }}"
        echo "security_token: ${{ steps.fetch-secrets.outputs.security_token }}"
        echo "ttl_in_minutes: ${{ steps.fetch-secrets.outputs.ttl_in_minutes }}"
        echo "type: ${{ steps.fetch-secrets.outputs.type }}"
        echo "user: ${{ steps.fetch-secrets.outputs.user }}"

    - name: Verify Environment Variables
      run: |
        echo "access_key_id: ${{ env.access_key_id }}"
        echo "id: ${{ env.id }}"
        echo "secret_access_key: ${{ env.secret_access_key }}"
        echo "security_token: ${{ env.security_token }}"
        echo "ttl_in_minutes: ${{ env.ttl_in_minutes }}"
        echo "type: ${{ env.type }}"
        echo "user: ${{ env.user }}"

  aws_dynamic_secrets_prefixed:
    runs-on: ubuntu-latest
    name: AWS dynamic secrets (prefixed)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from Akleyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/test-grib":"AWS"}' # applies "AWS_" prefix on output names
        parse-dynamic-secrets: true

    - name: Verify Job Outputs with Prefix
      run: |
        echo "access_key_id: ${{ steps.fetch-secrets.outputs.AWS_access_key_id }}"
        echo "id: ${{ steps.fetch-secrets.outputs-prefixed.AWS_id }}"
        echo "secret_access_key: ${{ steps.fetch-secrets.outputs.AWS_secret_access_key }}"
        echo "security_token: ${{ steps.fetch-secrets.outputs.AWS_security_token }}"
        echo "ttl_in_minutes: ${{ steps.fetch-secrets.outputs.AWS_ttl_in_minutes }}"
        echo "type: ${{ steps.fetch-secrets.outputs.AWS_type }}"
        echo "user: ${{ steps.fetch-secrets.outputs.AWS_user }}"

    - name: Verify Environment Variables with Prefix
      run: |
        echo "access_key_id: ${{ env.AWS_access_key_id }}"
        echo "id: ${{ env.AWS_id }}"
        echo "secret_access_key: ${{ env.AWS_secret_access_key }}"
        echo "security_token: ${{ env.AWS_security_token }}"
        echo "ttl_in_minutes: ${{ env.AWS_ttl_in_minutes }}"
        echo "type: ${{ env.AWS_type }}"
        echo "user: ${{ env.AWS_user }}"

  sql_dynamic_secrets:
    runs-on: ubuntu-latest
    name: SQL dynamic secrets (default)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from Akleyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/az-sqlsrvsecret":"my_dynamic_secret"}'

    - name: Verify Job Outputs using jq
      run: |
        echo "[Job Output] Your output secret is ${{ steps.fetch-secrets.outputs.my_dynamic_secret }}"
        echo "Manually parsed ID:" 
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq '.id'
        echo "Manually parsed USER:" 
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq '.user'
        echo "Manually parsed TTL_IN_MINUTES:" 
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo "Manually parsed PASSWORD:"
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq '.password'

    - name: Verify Environment Variables using jq
      run: |
        echo "[Env Var] Your environment secret is ${{ env.my_dynamic_secret }}"
        echo "Manually parsed ID:"
        echo '${{ env.my_dynamic_secret }}' | jq '.id'
        echo "Manually parsed USER:"
        echo '${{ env.my_dynamic_secret }}' | jq '.user'
        echo "Manually parsed TTL_IN_MINUTES:"
        echo 'Manually parsed ${{ env.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo "Manually parsed PASSWORD:"
        echo '${{ env.my_dynamic_secret }}' | jq '.password'

    - name: EXTRA 1 - Export Secrets to Environment using jq
      run: |
        echo '${{ steps.fetch-secrets.outputs.my_dynamic_secret }}' | jq -r 'to_entries|map("AKEYLESS_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
    
    - name: EXTRA 2 - Verify Exported Variables
      run: |
        echo "AKEYLESS_id = ${{ env.AKEYLESS_id }}"
        echo "AKEYLESS_user = ${{ env.AKEYLESS_user }}"
        echo "AKEYLESS_password = ${{ env.AKEYLESS_password }}"
        echo "AKEYLESS_ttl_in_minutes = ${{ env.AKEYLESS_ttl_in_minutes }}"

  sql_dynamic_secrets_parsed:
    runs-on: ubuntu-latest
    name: SQL dynamic secrets (parsed)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from Akleyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/test-grib":""}' # no prefix on output names
        parse-dynamic-secrets: true

    - name: Verify Job Outputs
      run: |
        echo "access_key_id: ${{ steps.fetch-secrets.outputs.access_key_id }}"
        echo "id: ${{ steps.fetch-secrets.outputs.id }}"
        echo "secret_access_key: ${{ steps.fetch-secrets.outputs.secret_access_key }}"
        echo "security_token: ${{ steps.fetch-secrets.outputs.security_token }}"
        echo "ttl_in_minutes: ${{ steps.fetch-secrets.outputs.ttl_in_minutes }}"
        echo "type: ${{ steps.fetch-secrets.outputs.type }}"
        echo "user: ${{ steps.fetch-secrets.outputs.user }}"

    - name: Verify Environment Variables
      run: |
        echo "access_key_id: ${{ env.access_key_id }}"
        echo "id: ${{ env.id }}"
        echo "secret_access_key: ${{ env.secret_access_key }}"
        echo "security_token: ${{ env.security_token }}"
        echo "ttl_in_minutes: ${{ env.ttl_in_minutes }}"
        echo "type: ${{ env.type }}"
        echo "user: ${{ env.user }}"

  sql_dynamic_secrets_prefixed:
    runs-on: ubuntu-latest
    name: SQL dynamic secrets (prefixed)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from Akleyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/az-sqlsrvsecret":"SQL"}' #applies "SQL_" prefix to output
        parse-dynamic-secrets: true

    - name: Verify Job Outputs with Prefix
      run: |
        echo "ID: ${{ steps.fetch-secrets.outputs.SQL_id }}" 
        echo "USER: ${{ steps.fetch-secrets.outputs.SQL_user }}" 
        echo "TTL_IN_MINUTES: ${{ steps.fetch-secrets.outputs.SQL_ttl_in_minutes }}" 
        echo "PASSWORD: ${{ steps.fetch-secrets.outputs.SQL_password }}"

    - name: Verify Environment Variables with Prefix
      run: |
        echo "ID: ${{ env.SQL_id }}"
        echo "USER: ${{ env.SQL_user }}"
        echo "TTL_IN_MINUTES: ${{ env.SQL_ttl_in_minutes }}"
        echo "PASSWORD: ${{ env.SQL_password }}"